
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 14;
  public static final int AND = 23;
  public static final int ELSE = 27;
  public static final int PLUS = 10;
  public static final int INT = 28;
  public static final int OR = 24;
  public static final int RBRACE = 7;
  public static final int RPAREN = 4;
  public static final int DEFINE = 8;
  public static final int THEN = 26;
  public static final int EQUAL = 20;
  public static final int NOTEQUAL = 21;
  public static final int SEMI = 5;
  public static final int NOT = 22;
  public static final int IF = 25;
  public static final int LPAREN = 3;
  public static final int LBRACE = 6;
  public static final int GREATERTHANEQUAL = 17;
  public static final int COMMA = 9;
  public static final int LESSTHAN = 18;
  public static final int EOF = 0;
  public static final int DIV = 13;
  public static final int MINUS = 11;
  public static final int error = 1;
  public static final int ASSIGN = 15;
  public static final int LESSTHANEQUAL = 19;
  public static final int MUL = 12;
  public static final int GREATERTHAN = 16;
  public static final int VAR = 29;
  public static final int FUN = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "FUN",
  "LPAREN",
  "RPAREN",
  "SEMI",
  "LBRACE",
  "RBRACE",
  "DEFINE",
  "COMMA",
  "PLUS",
  "MINUS",
  "MUL",
  "DIV",
  "MOD",
  "ASSIGN",
  "GREATERTHAN",
  "GREATERTHANEQUAL",
  "LESSTHAN",
  "LESSTHANEQUAL",
  "EQUAL",
  "NOTEQUAL",
  "NOT",
  "AND",
  "OR",
  "IF",
  "THEN",
  "ELSE",
  "INT",
  "VAR"
  };
}

